# Generated by Django 4.0.5 on 2022-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
            ],
        ),
    ]
