# Generated by Django 4.0.5 on 2022-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=10)),
                ('extraoption', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
